SistemaVentas/SistemaVentas/SistemaVentas/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaVentas.Models;
using System.Data.Entity;
using System.Net;

namespace SistemaVentas.Controllers
{
    public class ClienteController : Controller
    {
        VentasEntities db = new VentasEntities();

        // GET: Producto
        public ActionResult Index()
        {
            var listado = (from x in db.Cliente select x).ToList();
            return View(listado);
        }

        public ActionResult Create()
        {

            return View();
        }


        [HttpPost]
        public ActionResult Create(Cliente nuevoCliente)
        {

            db.Cliente.Add(nuevoCliente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var cliente = db.Cliente.Find(id);

            if (cliente == null)
                return HttpNotFound();


            return View(cliente);
        }

        [HttpPost]
        public ActionResult Edit(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                var clien = db.Cliente.Find(cliente.IdCliente);
                if (clien != null)
                {
                    clien.Nombre = cliente.Nombre;
                    clien.RUC = cliente.RUC;
                    clien.DNI = cliente.DNI;
                    clien.Direccion = cliente.Direccion;
                    clien.Telefono = cliente.Telefono;
                    clien.Observacion = cliente.Observacion;

                    db.Entry(clien).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "El producto no existe");
                    return View(cliente);
                }
            }
            else
            {

                return View(cliente);
            }
        }

        public ActionResult Details(int id)
        {
            var clie = db.Cliente.Find(id);
            return View(clie);
        }

        public ActionResult Delete(int? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var clie = db.Cliente.Find(id);

            if (clie == null)
                return HttpNotFound();

            return View(clie);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Cliente clie = db.Cliente.Find(id);
            db.Cliente.Remove(clie);
            db.SaveChanges();


            return RedirectToAction("Index");
        }



    }
}

SistemaVentas/SistemaVentas/SistemaVentas/Controllers/EmpleadoController.cs
using SistemaVentas.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SistemaVentas.Controllers
{
    public class EmpleadoController : Controller
    {
        VentasEntities db = new VentasEntities();
        // GET: Empleado
        public ActionResult Index()
        {
            var listado = (from x in db.Empleado select x).ToList();
            return View(listado);
        }

        public ActionResult Create()
        {
            ViewBag.IdTipoUsuario = new SelectList(db.TipoUsuario.ToList(), "IdTipoUsuario", "Descripcion");
            return View();
        }


        [HttpPost]
        public ActionResult Create(Empleado nuevoEnmpleado)
        {
            db.Empleado.Add(nuevoEnmpleado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? Id)
        {
            if (!Id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var emp = db.Empleado.Find(Id);
            
            if (emp == null)
                return HttpNotFound();

            ViewBag.IdTipoUsuario = new SelectList(db.TipoUsuario.ToList(), "IdTipoUsuario", "Descripcion", emp.IdTipoUsuario);
            return View(emp);
        }

        [HttpPost]
        public ActionResult Edit(Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                var emp = db.Empleado.Find(empleado.IdEmpleado);
                if (emp != null)
                {
                    emp.Nombre = empleado.Nombre;
                    emp.Apellido = empleado.Apellido;
                    emp.DNI = empleado.DNI;
                    emp.Direccion = empleado.Direccion;
                    emp.Telefono = empleado.Telefono;
                    emp.Usuario = empleado.Usuario;
                    emp.Clave = empleado.Clave;
                    emp.Observacion = empleado.Observacion;
                    emp.IdTipoUsuario = empleado.IdTipoUsuario;

                    db.Entry(emp).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "El tipo de usuario no existe");
                    ViewBag.IdTipoUsuario = new SelectList(db.TipoUsuario.ToList(), "IdTipoUsuario", "Descripcion", empleado.IdTipoUsuario);
                    return View(empleado);
                }
            }
            else
            {
                ViewBag.IdTipoUsuario = new SelectList(db.TipoUsuario.ToList(), "IdTipoUsuario", "Descripcion", empleado.IdTipoUsuario);
                return View(empleado);
            }
        }

        public ActionResult Details(int Id)
        {
            var emp = db.Empleado.Find(Id);
            return View(emp);
        }

        public ActionResult Delete(int? Id)
        {
            if (!Id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var emp = db.Empleado.Find(Id);

            if (emp == null)
                return HttpNotFound();

           return View(emp);
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            Empleado empl = db.Empleado.Find(Id);
            db.Empleado.Remove(empl);
            db.SaveChanges();

           
            return RedirectToAction("Index");
        }




    }
}

SistemaVentas/SistemaVentas/SistemaVentas/Controllers/ProductoController.cs
using SistemaVentas;
using SistemaVentas.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SistemaVentasPrueba.Controllers
{
    public class ProductoController : Controller
    {

        VentasEntities db = new VentasEntities();
        // GET: Producto
        public ActionResult Index()
        {

            var listado = (from x in db.Producto select x).ToList();
            return View(listado);

        }

        public ActionResult Create()
        {
            ViewBag.IdCategoria = new SelectList(db.Categoria.ToList(), "IdCategoria", "Descripcion");
            return View();
        }


        [HttpPost]
        public ActionResult Create(Producto nuevoProducto)
        {
            db.Producto.Add(nuevoProducto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? Id)
        {
            if (!Id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var emp = db.Producto.Find(Id);

            if (emp == null)
                return HttpNotFound();

            ViewBag.IdCategoria = new SelectList(db.Categoria.ToList(), "IdCategoria", "Descripcion", emp.IdCategoria);
            return View(emp);
        }

        [HttpPost]
        public ActionResult Edit(Producto Producto)
        {
            if (ModelState.IsValid)
            {
                var emp = db.Producto.Find(Producto.IdProducto);
                if (emp != null)
                {
                    emp.Nombre = Producto.Nombre;
                    emp.Descripcion = Producto.Descripcion;
                    emp.Marca = Producto.Marca;
                    emp.Stock = Producto.Stock;
                    emp.StockMinimo = Producto.StockMinimo;
                    emp.PrecioVenta = Producto.PrecioVenta;
                    emp.PrecioCosto = Producto.PrecioCosto;
                    emp.Utilidad = Producto.Utilidad;
                    emp.IdCategoria = Producto.IdCategoria;

                    db.Entry(emp).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "El Producto no existe");
                    ViewBag.IdCategoria = new SelectList(db.Categoria.ToList(), "IdCategoria", "Descripcion", Producto.IdCategoria);
                    return View(Producto);
                }
            }
            else
            {
                ViewBag.IdCategoria = new SelectList(db.Categoria.ToList(), "IdCategoria", "Descripcion", Producto.IdCategoria);
                return View(Producto);
            }
        }

        public ActionResult Details(int Id)
        {
            var emp = db.Producto.Find(Id);
            return View(emp);
        }

        public ActionResult Delete(int? Id)
        {
            if (!Id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var emp = db.Producto.Find(Id);

            if (emp == null)
                return HttpNotFound();

            return View(emp);
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            Producto empl = db.Producto.Find(Id);
            db.Producto.Remove(empl);
            db.SaveChanges();


            return RedirectToAction("Index");
        }



    }
}

SistemaVentas/SistemaVentas/SistemaVentas/Controllers/VentaController.cs
using SistemaVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SistemaVentas.Controllers
{
    public class VentaController : Controller
    {

        VentasEntities db = new VentasEntities();
        public ActionResult Index()
        {
            var listado = db.Venta.ToList();
            return View(listado);
        }

        public ActionResult Create()
        {
            ViewBag.IdCliente = new SelectList(db.Cliente.ToList(),"IdCliente","Nombre");
            ViewBag.IdEmpleado = new SelectList(db.Empleado.ToList(), "IdEmpleado", "Nombre");
            ViewBag.IdTipoComprobante = new SelectList(db.TipoComprobante.ToList(), "IdTipoComprobante", "Descripcion");
            return View();
        }

        public ActionResult Details(int? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var venta = (from x in db.Venta.ToList()
                       where x.IdVenta == id
                       select x).FirstOrDefault();
            if (venta == null)
                return HttpNotFound();
            return View(venta);
        }

    [HttpPost]
        public ActionResult Create(Venta venta,string operacion=null)
        {
            
            if (venta == null)
            {
                venta = new Venta();
            }

            if (operacion==null)
            {
                if (ModelState.IsValid)
                {
                    if (venta.DetalleVenta != null && venta.DetalleVenta.Count > 0)
                    {
                        venta.Fecha = DateTime.Now;

                        foreach (var item in venta.DetalleVenta)
                        {
                            venta.TotalPagar = venta.TotalPagar + (item.Cantidad * item.Precio);
                        }
                        
                        
                        db.Venta.Add(venta);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "La venta no tiene ningun producto");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "No se pudo grabar la venta");
                }
            }
            else if (operacion == "agregar")
            {

               
             
                venta.DetalleVenta.Add(new DetalleVenta());
                
            }
            else if (operacion.StartsWith("eliminar-"))
            {
                EliminarDetalle(venta, operacion);
            }
            ViewBag.IdCliente = new SelectList(db.Cliente.ToList(), "IdCliente", "Nombre",venta.IdCliente);
            ViewBag.IdEmpleado = new SelectList(db.Empleado.ToList(), "IdEmpleado", "Nombre",venta.IdEmpleado);
            ViewBag.IdTipoComprobante = new SelectList(db.TipoComprobante.ToList(), "IdTipoComprobante", "Descripcion",venta.IdTipoComprobante);
          
            ViewBag.Productos = db.Producto.ToList();
            return View(venta);
    }

    private void EliminarDetalle(Venta venta, string operacion)
    {
        string indexUrl = operacion.Replace("eliminar-","");
        int index = 0;

        if (int.TryParse(indexUrl,out index) && index>=0 && index<venta.DetalleVenta.Count)
        {
            var item = venta.DetalleVenta.ToArray()[index];
            venta.DetalleVenta.Remove(item);
        }
    }
	}
}

SistemaVentas/SistemaVentas/SistemaVentas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/misEstilos.css" rel="stylesheet" />
    <link href="~/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div id="wrapper">

        <!-- Navegavion -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Menu para disposotivos moviles -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">SB Admin</a>
            </div>
            <!-- Fin Menu para disposotivos moviles -->
            <!-- Menu Superior -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Usuario <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Perfil</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-power-off"></i> Cerrar Sesion</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!--Fin Menu Superior -->
            <!-- Menu lateral-->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">

                    <li class="active">
                        <a href="principal.html"><i class="fa fa-fw fa-dashboard"></i> Escritorio </a>
                    </li>


                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#almacen"><i class="fa fa-fw fa-edit"></i> Almacén <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="almacen" class="collapse">
                            <li>
                                <a href="@Url.Action("Index","Categoria")">Categorias</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","Producto")" >Producto</a>
                            </li>
                        </ul>
                    </li>


                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#ventas"><i class="fa fa-fw fa-file"></i> Ventas <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="ventas" class="collapse">
                            <li>
                                <a href="@Url.Action("Index","Cliente")" >Cliente</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Create","Venta")">Nueva Ventas</a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#cventas"><i class="fa fa-fw fa-bar-chart-o"></i> Consultas Ventas <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="cventas" class="collapse">
                            <li>
                                <a href="@Url.Action("Index","Venta")">Listado de Ventas</a>
                            </li>
                            
                        </ul>
                    </li>

                    

                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#mantenimiento"><i class="fa fa-fw fa-wrench"></i> Mantenimiento <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="mantenimiento" class="collapse">
                            <li>
                                <a href="@Url.Action("Index","Empleado")">Empleado</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","TipoUsuario")">Tipo Usuario</a>
                            </li>
                        </ul>
                    </li>

                    

                    <li>
                        <a href="index-rtl.html"><i class="fa fa-fw fa-clock-o"></i> Salir</a>
                    </li>
                </ul>
            </div>
            <!--Fin Menu Lateral-->
        </nav>
        <!--Fin Navegavion -->
        <!--Contenido-->
        <div id="page-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>